# Generated by Django 5.0.4 on 2026-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalunit',
            name='bed',
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='unit_type',
            field=models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('flat', 'Flat'), ('room', 'Room')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
