# Generated by Django 5.0.4 on 2026-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_rentalunit_bed_alter_rentalunit_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='occupancy_type',
            field=models.CharField(choices=[('shared', 'Shared'), ('exclusive', 'Exclusive')], default='shared', max_length=20),
        ),
    ]
