# Generated by Django 5.0.4 on 2026-07-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rentalunit_occupancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
