# Generated by Django 5.0.4 on 2026-07-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentalunit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='exclusive_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_rented_units', to='rent.users'),
        ),
    ]
